// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"gin-layout/internal/data/ent/greeterexample"
	"gin-layout/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GreeterExampleDelete is the builder for deleting a GreeterExample entity.
type GreeterExampleDelete struct {
	config
	hooks    []Hook
	mutation *GreeterExampleMutation
}

// Where appends a list predicates to the GreeterExampleDelete builder.
func (ged *GreeterExampleDelete) Where(ps ...predicate.GreeterExample) *GreeterExampleDelete {
	ged.mutation.Where(ps...)
	return ged
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ged *GreeterExampleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ged.sqlExec, ged.mutation, ged.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ged *GreeterExampleDelete) ExecX(ctx context.Context) int {
	n, err := ged.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ged *GreeterExampleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(greeterexample.Table, sqlgraph.NewFieldSpec(greeterexample.FieldID, field.TypeInt))
	if ps := ged.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ged.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ged.mutation.done = true
	return affected, err
}

// GreeterExampleDeleteOne is the builder for deleting a single GreeterExample entity.
type GreeterExampleDeleteOne struct {
	ged *GreeterExampleDelete
}

// Where appends a list predicates to the GreeterExampleDelete builder.
func (gedo *GreeterExampleDeleteOne) Where(ps ...predicate.GreeterExample) *GreeterExampleDeleteOne {
	gedo.ged.mutation.Where(ps...)
	return gedo
}

// Exec executes the deletion query.
func (gedo *GreeterExampleDeleteOne) Exec(ctx context.Context) error {
	n, err := gedo.ged.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{greeterexample.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gedo *GreeterExampleDeleteOne) ExecX(ctx context.Context) {
	if err := gedo.Exec(ctx); err != nil {
		panic(err)
	}
}
