// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gin-layout/internal/data/ent/greeterexample"
	"gin-layout/internal/data/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GreeterExampleQuery is the builder for querying GreeterExample entities.
type GreeterExampleQuery struct {
	config
	ctx        *QueryContext
	order      []greeterexample.OrderOption
	inters     []Interceptor
	predicates []predicate.GreeterExample
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GreeterExampleQuery builder.
func (geq *GreeterExampleQuery) Where(ps ...predicate.GreeterExample) *GreeterExampleQuery {
	geq.predicates = append(geq.predicates, ps...)
	return geq
}

// Limit the number of records to be returned by this query.
func (geq *GreeterExampleQuery) Limit(limit int) *GreeterExampleQuery {
	geq.ctx.Limit = &limit
	return geq
}

// Offset to start from.
func (geq *GreeterExampleQuery) Offset(offset int) *GreeterExampleQuery {
	geq.ctx.Offset = &offset
	return geq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (geq *GreeterExampleQuery) Unique(unique bool) *GreeterExampleQuery {
	geq.ctx.Unique = &unique
	return geq
}

// Order specifies how the records should be ordered.
func (geq *GreeterExampleQuery) Order(o ...greeterexample.OrderOption) *GreeterExampleQuery {
	geq.order = append(geq.order, o...)
	return geq
}

// First returns the first GreeterExample entity from the query.
// Returns a *NotFoundError when no GreeterExample was found.
func (geq *GreeterExampleQuery) First(ctx context.Context) (*GreeterExample, error) {
	nodes, err := geq.Limit(1).All(setContextOp(ctx, geq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{greeterexample.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (geq *GreeterExampleQuery) FirstX(ctx context.Context) *GreeterExample {
	node, err := geq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GreeterExample ID from the query.
// Returns a *NotFoundError when no GreeterExample ID was found.
func (geq *GreeterExampleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = geq.Limit(1).IDs(setContextOp(ctx, geq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{greeterexample.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (geq *GreeterExampleQuery) FirstIDX(ctx context.Context) int {
	id, err := geq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GreeterExample entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GreeterExample entity is found.
// Returns a *NotFoundError when no GreeterExample entities are found.
func (geq *GreeterExampleQuery) Only(ctx context.Context) (*GreeterExample, error) {
	nodes, err := geq.Limit(2).All(setContextOp(ctx, geq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{greeterexample.Label}
	default:
		return nil, &NotSingularError{greeterexample.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (geq *GreeterExampleQuery) OnlyX(ctx context.Context) *GreeterExample {
	node, err := geq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GreeterExample ID in the query.
// Returns a *NotSingularError when more than one GreeterExample ID is found.
// Returns a *NotFoundError when no entities are found.
func (geq *GreeterExampleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = geq.Limit(2).IDs(setContextOp(ctx, geq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{greeterexample.Label}
	default:
		err = &NotSingularError{greeterexample.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (geq *GreeterExampleQuery) OnlyIDX(ctx context.Context) int {
	id, err := geq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GreeterExamples.
func (geq *GreeterExampleQuery) All(ctx context.Context) ([]*GreeterExample, error) {
	ctx = setContextOp(ctx, geq.ctx, "All")
	if err := geq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GreeterExample, *GreeterExampleQuery]()
	return withInterceptors[[]*GreeterExample](ctx, geq, qr, geq.inters)
}

// AllX is like All, but panics if an error occurs.
func (geq *GreeterExampleQuery) AllX(ctx context.Context) []*GreeterExample {
	nodes, err := geq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GreeterExample IDs.
func (geq *GreeterExampleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if geq.ctx.Unique == nil && geq.path != nil {
		geq.Unique(true)
	}
	ctx = setContextOp(ctx, geq.ctx, "IDs")
	if err = geq.Select(greeterexample.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (geq *GreeterExampleQuery) IDsX(ctx context.Context) []int {
	ids, err := geq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (geq *GreeterExampleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, geq.ctx, "Count")
	if err := geq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, geq, querierCount[*GreeterExampleQuery](), geq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (geq *GreeterExampleQuery) CountX(ctx context.Context) int {
	count, err := geq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (geq *GreeterExampleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, geq.ctx, "Exist")
	switch _, err := geq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (geq *GreeterExampleQuery) ExistX(ctx context.Context) bool {
	exist, err := geq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GreeterExampleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (geq *GreeterExampleQuery) Clone() *GreeterExampleQuery {
	if geq == nil {
		return nil
	}
	return &GreeterExampleQuery{
		config:     geq.config,
		ctx:        geq.ctx.Clone(),
		order:      append([]greeterexample.OrderOption{}, geq.order...),
		inters:     append([]Interceptor{}, geq.inters...),
		predicates: append([]predicate.GreeterExample{}, geq.predicates...),
		// clone intermediate query.
		sql:  geq.sql.Clone(),
		path: geq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GreeterExample.Query().
//		GroupBy(greeterexample.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (geq *GreeterExampleQuery) GroupBy(field string, fields ...string) *GreeterExampleGroupBy {
	geq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GreeterExampleGroupBy{build: geq}
	grbuild.flds = &geq.ctx.Fields
	grbuild.label = greeterexample.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.GreeterExample.Query().
//		Select(greeterexample.FieldCreatedAt).
//		Scan(ctx, &v)
func (geq *GreeterExampleQuery) Select(fields ...string) *GreeterExampleSelect {
	geq.ctx.Fields = append(geq.ctx.Fields, fields...)
	sbuild := &GreeterExampleSelect{GreeterExampleQuery: geq}
	sbuild.label = greeterexample.Label
	sbuild.flds, sbuild.scan = &geq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GreeterExampleSelect configured with the given aggregations.
func (geq *GreeterExampleQuery) Aggregate(fns ...AggregateFunc) *GreeterExampleSelect {
	return geq.Select().Aggregate(fns...)
}

func (geq *GreeterExampleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range geq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, geq); err != nil {
				return err
			}
		}
	}
	for _, f := range geq.ctx.Fields {
		if !greeterexample.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if geq.path != nil {
		prev, err := geq.path(ctx)
		if err != nil {
			return err
		}
		geq.sql = prev
	}
	return nil
}

func (geq *GreeterExampleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GreeterExample, error) {
	var (
		nodes = []*GreeterExample{}
		_spec = geq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GreeterExample).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GreeterExample{config: geq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(geq.modifiers) > 0 {
		_spec.Modifiers = geq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, geq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (geq *GreeterExampleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := geq.querySpec()
	if len(geq.modifiers) > 0 {
		_spec.Modifiers = geq.modifiers
	}
	_spec.Node.Columns = geq.ctx.Fields
	if len(geq.ctx.Fields) > 0 {
		_spec.Unique = geq.ctx.Unique != nil && *geq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, geq.driver, _spec)
}

func (geq *GreeterExampleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(greeterexample.Table, greeterexample.Columns, sqlgraph.NewFieldSpec(greeterexample.FieldID, field.TypeInt))
	_spec.From = geq.sql
	if unique := geq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if geq.path != nil {
		_spec.Unique = true
	}
	if fields := geq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, greeterexample.FieldID)
		for i := range fields {
			if fields[i] != greeterexample.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := geq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := geq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := geq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := geq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (geq *GreeterExampleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(geq.driver.Dialect())
	t1 := builder.Table(greeterexample.Table)
	columns := geq.ctx.Fields
	if len(columns) == 0 {
		columns = greeterexample.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if geq.sql != nil {
		selector = geq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if geq.ctx.Unique != nil && *geq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range geq.modifiers {
		m(selector)
	}
	for _, p := range geq.predicates {
		p(selector)
	}
	for _, p := range geq.order {
		p(selector)
	}
	if offset := geq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := geq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (geq *GreeterExampleQuery) Modify(modifiers ...func(s *sql.Selector)) *GreeterExampleSelect {
	geq.modifiers = append(geq.modifiers, modifiers...)
	return geq.Select()
}

// GreeterExampleGroupBy is the group-by builder for GreeterExample entities.
type GreeterExampleGroupBy struct {
	selector
	build *GreeterExampleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gegb *GreeterExampleGroupBy) Aggregate(fns ...AggregateFunc) *GreeterExampleGroupBy {
	gegb.fns = append(gegb.fns, fns...)
	return gegb
}

// Scan applies the selector query and scans the result into the given value.
func (gegb *GreeterExampleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gegb.build.ctx, "GroupBy")
	if err := gegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GreeterExampleQuery, *GreeterExampleGroupBy](ctx, gegb.build, gegb, gegb.build.inters, v)
}

func (gegb *GreeterExampleGroupBy) sqlScan(ctx context.Context, root *GreeterExampleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gegb.fns))
	for _, fn := range gegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gegb.flds)+len(gegb.fns))
		for _, f := range *gegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GreeterExampleSelect is the builder for selecting fields of GreeterExample entities.
type GreeterExampleSelect struct {
	*GreeterExampleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ges *GreeterExampleSelect) Aggregate(fns ...AggregateFunc) *GreeterExampleSelect {
	ges.fns = append(ges.fns, fns...)
	return ges
}

// Scan applies the selector query and scans the result into the given value.
func (ges *GreeterExampleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ges.ctx, "Select")
	if err := ges.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GreeterExampleQuery, *GreeterExampleSelect](ctx, ges.GreeterExampleQuery, ges, ges.inters, v)
}

func (ges *GreeterExampleSelect) sqlScan(ctx context.Context, root *GreeterExampleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ges.fns))
	for _, fn := range ges.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ges.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ges.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ges *GreeterExampleSelect) Modify(modifiers ...func(s *sql.Selector)) *GreeterExampleSelect {
	ges.modifiers = append(ges.modifiers, modifiers...)
	return ges
}
