// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GreeterExample is the predicate function for greeterexample builders.
type GreeterExample func(*sql.Selector)
