// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: greeter.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Greeter with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Greeter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Greeter with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in GreeterMultiError, or nil if none found.
func (m *Greeter) ValidateAll() error {
	return m.validate(true)
}

func (m *Greeter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return GreeterMultiError(errors)
	}

	return nil
}

// GreeterMultiError is an error wrapping multiple validation errors returned
// by Greeter.ValidateAll() if the designated constraints aren't met.
type GreeterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GreeterMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GreeterMultiError) AllErrors() []error { return m }

// GreeterValidationError is the validation error returned by Greeter.Validate
// if the designated constraints aren't met.
type GreeterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GreeterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GreeterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GreeterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GreeterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GreeterValidationError) ErrorName() string { return "GreeterValidationError" }

// Error satisfies the builtin error interface
func (e GreeterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGreeter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GreeterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GreeterValidationError{}

// Validate checks the field values on CreateGreeterRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateGreeterRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateGreeterRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateGreeterRequestMultiError, or nil if none found.
func (m *CreateGreeterRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateGreeterRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CreateGreeterRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateGreeterRequestMultiError(errors)
	}

	return nil
}

// CreateGreeterRequestMultiError is an error wrapping multiple validation
// errors returned by CreateGreeterRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateGreeterRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateGreeterRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateGreeterRequestMultiError) AllErrors() []error { return m }

// CreateGreeterRequestValidationError is the validation error returned by
// CreateGreeterRequest.Validate if the designated constraints aren't met.
type CreateGreeterRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateGreeterRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateGreeterRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateGreeterRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateGreeterRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateGreeterRequestValidationError) ErrorName() string {
	return "CreateGreeterRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateGreeterRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateGreeterRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateGreeterRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateGreeterRequestValidationError{}

// Validate checks the field values on CreateGreeterReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateGreeterReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateGreeterReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateGreeterReplyMultiError, or nil if none found.
func (m *CreateGreeterReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateGreeterReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGreeter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateGreeterReplyValidationError{
					field:  "Greeter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateGreeterReplyValidationError{
					field:  "Greeter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGreeter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateGreeterReplyValidationError{
				field:  "Greeter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateGreeterReplyMultiError(errors)
	}

	return nil
}

// CreateGreeterReplyMultiError is an error wrapping multiple validation errors
// returned by CreateGreeterReply.ValidateAll() if the designated constraints
// aren't met.
type CreateGreeterReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateGreeterReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateGreeterReplyMultiError) AllErrors() []error { return m }

// CreateGreeterReplyValidationError is the validation error returned by
// CreateGreeterReply.Validate if the designated constraints aren't met.
type CreateGreeterReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateGreeterReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateGreeterReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateGreeterReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateGreeterReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateGreeterReplyValidationError) ErrorName() string {
	return "CreateGreeterReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateGreeterReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateGreeterReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateGreeterReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateGreeterReplyValidationError{}
