// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GreeterExamplesColumns holds the columns for the "greeter_examples" table.
	GreeterExamplesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// GreeterExamplesTable holds the schema information for the "greeter_examples" table.
	GreeterExamplesTable = &schema.Table{
		Name:       "greeter_examples",
		Columns:    GreeterExamplesColumns,
		PrimaryKey: []*schema.Column{GreeterExamplesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GreeterExamplesTable,
	}
)

func init() {
}
