// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-layout/internal/cache"
	"gin-layout/internal/conf"
	"gin-layout/internal/data"
	"gin-layout/internal/log"
	"gin-layout/internal/middlewares"
	"gin-layout/internal/robot"
	"gin-layout/internal/services"
	"github.com/trumanwong/gin-transport/v2/transport"
)

// Injectors from wire.go:

func wireApp() *transport.Server {
	configs := conf.NewConfig()
	logger := log.NewLogger()
	workWechatRobot := robot.NewRobotWechat(configs)
	middleware := middlewares.NewMiddleware(configs, logger, workWechatRobot)
	client := data.NewEntClient(configs)
	dataData := data.NewData(client)
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	cacheCache := cache.NewCache(configs)
	appService := services.NewAppService(greeterRepo, cacheCache, configs, logger, workWechatRobot)
	server := NewHttpServer(configs, logger, middleware, appService)
	return server
}
