// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-layout/internal/cache"
	"gin-layout/internal/conf"
	"gin-layout/internal/data"
	"gin-layout/internal/log"
	"gin-layout/internal/middlewares"
	"gin-layout/internal/robot"
	"gin-layout/internal/services"
)

// Injectors from wire.go:

func wireApp() *AppService {
	configs := conf.NewConfig()
	client := data.NewEntClient(configs)
	dataData := data.NewData(client)
	logger := log.NewLogger()
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	cacheCache := cache.NewCache(configs)
	workWechatRobot := robot.NewRobotWechat(configs)
	appService := services.NewAppService(greeterRepo, cacheCache, configs, logger, workWechatRobot)
	middleware := middlewares.NewMiddleware(configs, logger, workWechatRobot)
	mainAppService := newApp(appService, configs, logger, middleware)
	return mainAppService
}
