services:
  gin-layout-server:
    container_name: gin-layout-server
    image: docker.io/trumanwong/gin-layout-server:1.0.0
    ports:
      - "24720:8000"
    env_file: .env
    restart: always
    privileged: true
    volumes:
      - ../configs:/configs
      - ../../templates:/templates
      - ../../logs:/logs
      - ../../storage:/storage
      - ../../supervisor/conf.d:/etc/supervisor/conf.d
